sample_board/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('welcome', views.welcome, name='welcome'),
    path('new_regist', views.new_regist, name='new_regist'),
    path('home', views.home, name='home'),
    path('regist', views.regist, name='regist'),
    path('login', views.login_user, name='login'),
    path('edit', views.edit_user, name='edit'),
    path('delete/<int:id>', views.delete_user, name='delete'),
    path('logout', views.logout_user, name='logout'),
    path('welcome', views.home, name='welcome'), 
    path('change_password', views.change_password, name='change_password'), 
]

sample_board/boards/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name = 'boards'


urlpatterns = [
    path('create_theme', views.create_theme, name='create_theme'),
    path('list_themes', views.list_themes, name='list_themes'),
    path('search_themes', views.search_themes, name='search_themes'),
    path('edit_theme/<int:id>', views.edit_theme, name='edit_theme'),
    path('delete_theme/<int:id>', views.delete_theme, name='delete_theme'),
    path('post_comments/<int:theme_id>', views.post_comments, name='post_comments'),
    path('edit_comment/<int:id>', views.edit_comment, name='edit_comment'),
    path('delete_comment/<int:id>', views.delete_comment, name='delete_comment'),
    path('download/<int:id>', views.download, name='download'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sample_board/sample_board/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('boards/', include('boards.urls')),
]

sample_board/boards/models.py
from django.db import models

# Create your models here.
class ThemesManager(models.Manager):

    def fetch_all_themes(self):
        return self.order_by('id').all()
    

class Themes(models.Model):

    title = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(
        'accounts.Users', on_delete=models.CASCADE
    )

    objects = ThemesManager()

    class Meta:
        db_table = 'themes'


class CommentsManager(models.Manager):
    def fetch_by_theme_id(self, theme_id):
        return self.filter(theme_id=theme_id).order_by('id').all()

class Comments(models.Model):
    
    comment = models.CharField(max_length=1000)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey('accounts.Users', on_delete=models.CASCADE)
    theme = models.ForeignKey('Themes', on_delete=models.CASCADE)
    attach = models.FileField(verbose_name='添付ファイル',upload_to='media/%Y/%m/%d/',blank=True, null=True)

    objects = CommentsManager()

    class Meta:
        db_table = 'comments'


sample_board/boards/forms.py
from django import forms
from .models import Themes, Comments


class CreateThemeForm(forms.ModelForm):
    title = forms.CharField(label='タイトル')
    class Meta:
        model = Themes
        fields = ('title',)


class DeleteThemeForm(forms.ModelForm):

    class Meta:
        model = Themes
        fields = []

class PostCommentForm(forms.ModelForm):
    comment = forms.CharField(label='コメント', widget=forms.Textarea(attrs={'rows':5, 'cols':60}))
    attach = forms.FileField(label='添付ファイル', required=False, )
    class Meta:
        model = Comments
        fields = ('comment', 'attach')

class DeleteCommentForm(forms.ModelForm):
    
    class Meta:
        model = Comments
        fields = []



sample_board/boards/views.py
import mimetypes
import shutil
import mojimoji
from django.shortcuts import render, redirect, get_object_or_404
from . import forms
from .models import Themes, Comments
from django.http import Http404
from django.contrib import messages
from django.core.paginator import Paginator
from django.http import HttpResponse




#掲示板作成
def create_theme(request):
    create_theme_form = forms.CreateThemeForm(request.POST or None)
    if create_theme_form.is_valid(): #formsで作成する必要あり
        create_theme_form.instance.user = request.user
        create_theme_form.save()
        messages.success(request, '掲示板を作成しました')
        return redirect('boards:list_themes')
    
    return render(
        request, 'boards/create_theme.html', context={
            'create_theme_form': create_theme_form
        }
    )

#掲示板一覧
def list_themes(request):
    themes_list = Themes.objects.fetch_all_themes().order_by('-id')
    #ページネーション 
    p = Paginator(themes_list, 5) #5つで1ページ
    page = request.GET.get('page') #リクエストページ
    pages = p.get_page(page)
    return render(
        request, 'boards/list_themes.html', context={
            
            'pages': pages
        }
    )

#数字だけ半角→全角変換の関数
def number_only_replace_zen_han(self):
    transTable = self.maketrans("０１２３４５６７８９", "0123456789")
    self = self.translate(transTable)
    return self

#検索機能
def search_themes(request): 
    query = request.GET.get(str('query')) #query(検索に入力された言葉)を取得
    queryset = Themes.objects.fetch_all_themes().order_by('-id') #querysetにThemesモデルのデータを全て格納
    if query: #もし検索ワードあれば
        query = mojimoji.han_to_zen(query)
        print(f'{query}1')
        queryset = queryset.filter(title__icontains=query) #タイトルを検索ワードでフィルターかけてthemesデータを抽出
        print(queryset)
        if len(queryset) == 0:
            queryset = Themes.objects.fetch_all_themes().order_by('-id')
            query = number_only_replace_zen_han(query)
            print(f'{query}2')
            queryset = queryset.filter(title__icontains=query) #タイトルを検索ワードでフィルターかけてthemesデータを抽出
            if len(queryset) == 0:
                queryset = Themes.objects.fetch_all_themes().order_by('-id')
                query = mojimoji.zen_to_han(query)
                print(f'{query}3')
                queryset = queryset.filter(title__icontains=query) #タイトルを検索ワードでフィルターかけてthemesデータを抽出
    return render(
    request, 'boards/search_themes.html', context={
        'query': query,
        'queryset': queryset,         
        }
    )
    


#掲示板更新
def edit_theme(request, id):
    theme = get_object_or_404(Themes, id=id)
    if theme.user.id != request.user.id:
        raise Http404
    edit_theme_form = forms.CreateThemeForm(request.POST or None, instance=theme)
    if edit_theme_form.is_valid():
        edit_theme_form.save()
        messages.success(request, '掲示板を更新しました')
        return redirect('boards:list_themes')
    return render(
        request, 'boards/edit_theme.html', context={
            'edit_theme_form': edit_theme_form,
            'id': id,
        }
    )

#掲示板削除
def delete_theme(request, id):
    theme = get_object_or_404(Themes, id=id)
    if theme.user.id !=request.user.id:
        raise Http404
    delete_theme_form = forms.DeleteThemeForm(request.POST or None)
    if delete_theme_form.is_valid():
        theme.delete()
        messages.success(request, '掲示板を削除しました')
        return redirect('boards:list_themes')
    return render(
        request, 'boards/delete_theme.html', context={
            'delete_theme_form': delete_theme_form
        }
    )


#コメント投稿
def post_comments(request, theme_id):
    post_comment_form = forms.PostCommentForm(request.POST or None,)
    theme = get_object_or_404(Themes, id=theme_id)
    comments = Comments.objects.fetch_by_theme_id(theme_id).order_by('-created_at')
    if post_comment_form.is_valid():
        if not request.user.is_authenticated:
            raise Http404
        post_comment_form.instance.theme = theme
        post_comment_form.instance.user = request.user
        if post_comment_form.instance.attach:
            post_comment_form.instance.attach = request.FILES['attach']
        post_comment_form.save()
        return redirect('boards:post_comments', theme_id=theme_id)
    return render(
        request, 'boards/post_comments.html', context={
            'post_comment_form': post_comment_form,
            'theme': theme,
            'comments': comments,
        }
    )

#コメント更新
def edit_comment(request, id):
    comment = get_object_or_404(Comments, id=id)
    if comment.user.id != request.user.id:
        raise Http404
    edit_comment_form = forms.PostCommentForm(request.POST or None, instance=comment)
    if edit_comment_form.is_valid():
        edit_comment_form.save()
        theme_id = comment.theme.id
        messages.success(request, 'コメントを更新しました')
        return redirect('boards:post_comments', theme_id)
    return render(
        request, 'boards/edit_comment.html', context={
            'edit_comment_form': edit_comment_form,
            'id': id,
        }
    )

#コメント削除
def delete_comment(request, id):
    comment = get_object_or_404(Comments, id=id)
    if comment.user.id !=request.user.id:
        raise Http404
    delete_comment_form = forms.DeleteCommentForm(request.POST or None)
    if delete_comment_form.is_valid():
        theme_id = comment.theme.id
        comment.delete()
        
        messages.success(request, 'コメントを削除しました')
        return redirect('boards:post_comments', theme_id)
    return render(
        request, 'boards/delete_comment.html', context={
            'delete_comment_form': delete_comment_form
        }
    )
        
#ファイルダウンロード機能
def download(request, id):
    upload_file = get_object_or_404(Comments, id=id)
    file = upload_file.attach  # ファイル本体
    name = file.name  # ファイル名
    response = HttpResponse(content_type=mimetypes.guess_type(name)[0] or 'application/octet-stream') # ファイル名からmimetypeを推測。拡張子がないファイル等は、application/octet-stream
    response['Content-Disposition'] = f'attachment; filename={name}' # Content-Dispositionでダウンロードの強制
    shutil.copyfileobj(file, response) # HttpResponseに、ファイルの内容を書き込む
    return response






sample_board/templates/boards/create_theme.html
{% extends "base.html" %}
{% block content %}
<h1>掲示板作成画面</h1>
<form method="POST">
{% csrf_token %}
{{ create_theme_form.as_p }}
<div class="buttons">
    <input class="execution-button" type="submit" value="掲示板作成">
    <a class="return-button" href="{% url 'accounts:home' %}">ホーム画面に戻る</a>
</div>
</form>

{% endblock %}

sample_board/templates/boards/delete_comment.html
{% extends "base.html" %}
{% block content %}
<h1>コメント削除画面</h1>
<form method="POST">
{% csrf_token %}
{{ delete_comment_form.as_p }}
<div class="buttons">
    <input class="delete-button" type="submit" value="削除する">
    <a class="return-button" href="{% url 'accounts:home' %}">ホームに戻る</a>
</div>
</form>
{% endblock %}

sample_board/templates/boards/delete_theme.html
{% extends "base.html" %}
{% block content %}
<h1>掲示板削除画面</h1>
<form method="POST">
{% csrf_token %}
{{ delete_theme_form.as_p }}
<div class="buttons">
    <input class="delete-button" type="submit" value="削除する">
    <a class="return-button" href="{% url 'boards:list_themes' %}">戻る</a>
</div>
</form>
{% endblock %}

sample_board/templates/boards/download.html
{% for file in uploadfile %}
        <a href="{% url 'boards:download' theme.id %}">{{ uploadfile }}</a>
        <hr>
{% endfor %}

sample_board/templates/boards/edit_comment.html
{% extends "base.html" %}
{% block content %}
<h1>コメント編集</h1>
<form method="POST">
{% csrf_token %}
{{ edit_comment_form.as_p }}
<div class="buttons">
    <input class="execution-button" type="submit" value="コメント更新">
    <a class="return-button" href="{% url 'accounts:home' %}">ホームに戻る</a>
    <a class="delete-button" href="{% url 'boards:delete_comment' id=id %}">コメント削除</a>
</div>
</form>
{% endblock %}

sample_board/templates/boards/edit_theme.html
{% extends "base.html" %}
{% block content %}
<h1>掲示板編集</h1>
<form method="POST">
{% csrf_token %}
{{ edit_theme_form.as_p }}
<div class="buttons">
    <input class="execution-button" type="submit" value="掲示板更新">
    <a class="return-button" href="{% url 'accounts:home' %}">ホームに戻る</a>
    <a class="delete-button" href="{% url 'boards:delete_theme' id=id %}">掲示板削除</a>
</div>
</form>
{% endblock %}

sample_board/templates/boards/list_themes.html
{% extends "base.html" %}
{% block content %}
{% if messages %}
    {% for message in messages %}
        <div>{{ message.message }}</div>
    {% endfor %}
{% endif %}
<h1>掲示板"一覧"画面</h1>
{% if user.is_authenticated %}
    {% if user.status == "teacher" %}
        <div><a class="execution-button" href="{% url 'boards:create_theme' %}">掲示板を新たに作成</a></div>
    {% endif %}
{% endif %}
<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th>掲示板番号</th>
            <th>作成日</th>
            <th>タイトル</th>
            <th>作成者</th>
        </tr>
    </thead>
    <tbody>
    {% for theme in pages %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ theme.created_at|date:"Y/m/d" }}</td>
            <td><a href="{% url 'boards:post_comments' theme_id=theme.id%}">{{ theme.title }}</a></td>
            {% if theme.user.id == user.id %}
                <td><a href="{% url 'boards:edit_theme' id=theme.id %}">{{ theme.user }}先生</a></td>
            {% else %}
                <td>{{ theme.user }}先生</td>
            {% endif %}
        </tr>
    {% endfor %}
    </tbody>
    
</table>

{% if pages.has_other_pages %}
    <nav aria-label="Page navigation example">
        <ul class="pagination">
            {% if pages.has_previous %}
                <li><a class="page-link text-primary d-inline-block" href="?page={{ pages.previous_page_number }}"><<</a></li>
            {% else %}
                <li class="disabled"><a id="link" class="page-link text-secondary d-inline-block disabled" href="#"><<</a></li>
            {% endif %}

            {% for page_num in pages.paginator.page_range %}
                {% if page_num %}
                    {% if page_num == pages.number %}
                        <li class="disabled"><a id="link" class="page-link text-secondary d-inline-block disabled" href="#">{{ page_num }}</a></li>
                    {% else %}
                        <li><a class="page-link text-primary d-inline-block" href="?page={{ page_num }}">{{ page_num }}</a></li>
                    {% endif %}
                {% else %}
                    <li class="disabled"><a class="page-link text-secondary d-inline-block text-muted" href="#">・・・</a></li>
                {% endif %}
            {% endfor %}

            {% if pages.has_next %}
                <li><a class="page-link text-primary d-inline-block" href="?page={{ pages.next_page_number }}">>></a></li>
            {% else %}
                <li class="disabled"><a id="link" class="page-link text-secondary d-inline-block disabled" href="#">>></a></li>
            {% endif %}
        </ul>
    </nav>
{% endif %}

<a class="return-button" href="{% url 'accounts:home' %}">ホームに戻る</a>

<div><p>タイトルをクリックすると、その掲示板の中の詳細画面にうつります。<br>
掲示板の作成、コメントの送信は「先生」のユーザーしかできません。
掲示板の作成者のみ、作成者の名前をクリックできるようになり、掲示板の編集、削除ができます。</p></div>
{% endblock %}

sample_board/templates/boards/post_comments.html
{% extends "base.html" %}
{% block content %}
<h1>{{ theme.title }}</h1>
{% for comment in comments %} 
    <div id="comment">
    <p>名前：{{ comment.user.first_name }}先生</p>
    <p>投稿日：{{ comment.created_at | date:"Y/m/d" }}</p>
    <p>投稿内容：{{ comment.comment }}</p>
        {% if comment.attach %}
        <p>添付ファイル：<a href="{% url 'boards:download' id=comment.id %}">添付ファイルを表示</a></p>
        {% endif %}
    {% if comment.user.id == user.id %}
    <a class="execution-button" href="{% url 'boards:edit_comment' id=comment.id %}">コメント編集</a>
    <a class="delete-button" href="{% url 'boards:delete_comment' id=comment.id %}">コメント削除</a>
    {% endif %}
    </div>
{% endfor %}
    
{% if user.is_authenticated %}
    {% if user.status == "teacher" %}
    <div id="post_comment">
        <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ post_comment_form.as_p }}
    
        <input class="execution-button" type="submit" value="投稿">
        </form>
    </div>
    {% endif %}
{% endif %}

<a class="return-button" href="{% url 'boards:list_themes' %}">掲示板一覧画面に戻る</a>
{% endblock %}

sample_board/templates/boards/search_themes.html
{% extends "base.html" %}
{% block content %}
<h1>掲示板"検索"画面</h1>
<form method="GET">
<div>
<input type="search" value="{{ request.GET.query }}" 
         name="query" type="text" 
         placeholder=" 掲示板のタイトル検索 ">
<button>検索</button>
</div>

<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th>掲示板番号</th>
            <th>作成日</th>
            <th>タイトル</th>
            <th>作成者</th>
        </tr>
    </thead>
    <tbody>
    {% for theme in queryset %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ theme.created_at|date:"Y/m/d" }}</td>
            <td><a href="{% url 'boards:post_comments' theme_id=theme.id %}">{{ theme.title }}</a></td>
            {% if theme.user.id == user.id %}
                <td><a href="{% url 'boards:edit_theme' id=theme.id %}">{{ theme.user }}先生</a></td>
            {% else %}
                <td>{{ theme.user }}</td>
            {% endif %}
        </tr>
    {% endfor %}

    {% if queryset.has_other_pages %}
    <nav aria-label="Page navigation example">
        <ul class="pagination">
            {% if queryset.has_previous %}
                <li><a class="page-link text-primary d-inline-block" href="?page={{ queryset.previous_page_number }}"><<</a></li>
            {% else %}
                <li class="disabled"><div class="page-link text-secondary d-inline-block disabled" href="#"><<</div></li>
            {% endif %}

            {% for page_num in queryset.paginator.page_range %}
                {% if page_num %}
                    {% if page_num == queryset.number %}
                        <li class="disabled"><div class="page-link text-secondary d-inline-block disabled" href="#">{{ page_num }}</div></li>
                    {% else %}
                        <li><a class="page-link text-primary d-inline-block" href="?page={{ page_num }}">{{ page_num }}</a></li>
                    {% endif %}
                {% else %}
                    <li class="disabled"><a class="page-link text-secondary d-inline-block text-muted" href="#">・・・</a></li>
                {% endif %}
            {% endfor %}

            {% if queryset.has_next %}
                <li><a class="page-link text-primary d-inline-block" href="?page={{ queryset.next_page_number }}">>></a></li>
            {% else %}
                <li class="disabled"><div class="page-link text-secondary d-inline-block disabled" href="#">>></div></li>
            {% endif %}
        </ul>
    </nav>
    {% endif %}

    </tbody>
</table>

<a class="return-button" href="{% url 'accounts:home' %}">ホームに戻る</a>
{% endblock %}