sample_board/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('welcome', views.welcome, name='welcome'),
    path('new_regist', views.new_regist, name='new_regist'),
    path('home', views.home, name='home'),
    path('regist', views.regist, name='regist'),
    path('login', views.login_user, name='login'),
    path('edit', views.edit_user, name='edit'),
    path('delete/<int:id>', views.delete_user, name='delete'),
    path('logout', views.logout_user, name='logout'),
    path('welcome', views.home, name='welcome'), 
    path('change_password', views.change_password, name='change_password'), 
]

sample_board/boards/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name = 'boards'


urlpatterns = [
    path('create_theme', views.create_theme, name='create_theme'),
    path('list_themes', views.list_themes, name='list_themes'),
    path('search_themes', views.search_themes, name='search_themes'),
    path('edit_theme/<int:id>', views.edit_theme, name='edit_theme'),
    path('delete_theme/<int:id>', views.delete_theme, name='delete_theme'),
    path('post_comments/<int:theme_id>', views.post_comments, name='post_comments'),
    path('edit_comment/<int:id>', views.edit_comment, name='edit_comment'),
    path('delete_comment/<int:id>', views.delete_comment, name='delete_comment'),
    path('download/<int:id>', views.download, name='download'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sample_board/sample_board/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('boards/', include('boards.urls')),
]

sample_board/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ja">
    <head>
        <meta charset="utf-8">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        
        <title>学校連絡掲示板</title>
    </head>
    <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'accounts:home' %}">ホーム</a>
            {% if user.is_authenticated %}
                <a class="navbar-brand" href="{% url 'accounts:logout' %}">ログアウト</a>
                <a class="navbar-brand" href="{% url 'accounts:edit' %}">ユーザ情報更新</a>
                <a class="navbar-brand" href="{% url 'boards:list_themes' %}">掲示板一覧</a>
                <a class="navbar-brand" href="{% url 'boards:search_themes' %}">掲示板検索</a>
            {% else %}
                <a class="navbar-brand" href="{% url 'accounts:login' %}">ログイン</a>
                
            {% endif %}
    </nav>
    {% if user.status == "teacher" %}
        <div id="username">こんにちは! {{user.first_name}} 先生</div>
    {% else %}
        <div id="username">こんにちは! {{user.first_name}} さん</div>
    {% endif %}
    {% block content %}{% endblock %}
    </body>
</html>