sample_board/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('welcome', views.welcome, name='welcome'),
    path('new_regist', views.new_regist, name='new_regist'),
    path('home', views.home, name='home'),
    path('regist', views.regist, name='regist'),
    path('login', views.login_user, name='login'),
    path('edit', views.edit_user, name='edit'),
    path('delete/<int:id>', views.delete_user, name='delete'),
    path('logout', views.logout_user, name='logout'),
    path('welcome', views.home, name='welcome'), 
    path('change_password', views.change_password, name='change_password'), 
]

sample_board/boards/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name = 'boards'


urlpatterns = [
    path('create_theme', views.create_theme, name='create_theme'),
    path('list_themes', views.list_themes, name='list_themes'),
    path('search_themes', views.search_themes, name='search_themes'),
    path('edit_theme/<int:id>', views.edit_theme, name='edit_theme'),
    path('delete_theme/<int:id>', views.delete_theme, name='delete_theme'),
    path('post_comments/<int:theme_id>', views.post_comments, name='post_comments'),
    path('edit_comment/<int:id>', views.edit_comment, name='edit_comment'),
    path('delete_comment/<int:id>', views.delete_comment, name='delete_comment'),
    path('download/<int:id>', views.download, name='download'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sample_board/sample_board/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('boards/', include('boards.urls')),
]

sample_board/accounts/models.py
from django.db import models
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser, PermissionsMixin
)
# Create your models here.

class UserManager(BaseUserManager):
    def create_user(
            self,
            school_id,
            class_id,
            first_name,
            last_name,
            first_name_phonetic,
            last_name_phonetic,
            birthday,
            school_grade,
            school_class,
            email,
            club,
            gender,
            status,
            password=None
        ):
        
        user = self.model(
            school_id=school_id,
            class_id=class_id,
            first_name=first_name,
            last_name=last_name,
            first_name_phonetic=first_name_phonetic,
            last_name_phonetic=last_name_phonetic,
            birthday=birthday,
            school_grade=school_grade,
            school_class=school_class,
            email=email,
            club=club,
            gender=gender,
            status=status,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user
    
    #スーパーユーザーの入力項目(管理者用)
    def create_superuser(
            self,
            school_id,
            first_name,
            last_name,
            birthday,
            status,
            password=None
        ):

        user = self.model(
            school_id=school_id,
            first_name=first_name,
            last_name=last_name,
            birthday=birthday,
            status=status,
        )

        user.set_password(password)
        user.is_staff = True
        user.is_active = True 
        user.is_superuser = True 
        user.save(using=self._db) 
        return user

#ユーザーモデル(教師、生徒含む)
class Users(AbstractBaseUser, PermissionsMixin):
    school_id = models.IntegerField(unique=True) #ユーザーid
    class_id = models.IntegerField(blank=True, null=True) #出席番号、教師は出席番号をもたないため、必須にはしない。
    first_name = models.CharField(max_length=150) #姓
    last_name = models.CharField(max_length=150) #名
    first_name_phonetic = models.CharField(max_length=150) #姓ふりがな
    last_name_phonetic = models.CharField(max_length=150) #名ふりがな
    birthday = models.DateField() #誕生日
    school_grade = models.PositiveIntegerField(blank=True, null=True) #学年
    school_class = models.PositiveIntegerField(blank=True, null=True) #組
    email = models.EmailField(max_length=150, blank=True, null=True) #学生はメアド持ってない場合があることを想定して必須項目にしない。
    club = models.CharField(max_length=150, blank=True, null=True) #帰宅部想定でnull=True
    is_active = models.BooleanField(default=True) #認証登録は今回は省くためdefault=True
    is_staff = models.BooleanField(default=False) 
    created_at = models.DateTimeField(auto_now_add=True) #登録日時
    updated_at = models.DateTimeField(auto_now=True) #更新日時
    GENDER_CHOICES = (
        ('man', 'Man'),
        ('woman', 'Woman'),
    )
    STATUS_CHOICES = (
        ('teacher', 'Teacher'),
        ('student', 'Student'),
    )
    gender = models.CharField(max_length=50, choices=GENDER_CHOICES) #性別
    status = models.CharField(max_length=50, choices=STATUS_CHOICES) #立場

    USERNAME_FIELD = 'school_id'
    REQUIRED_FIELDS = ['first_name', 'last_name','status','birthday'] 

    objects = UserManager() 

    class Meta:
        db_table = 'users' 
    
    def __str__(self):
        return f'{self.school_grade}年{self.school_class}組 : {self.first_name} {self.last_name}' 
    


sample_board/accounts/forms.py
from django import forms
from .models import Users
from django.contrib.auth.password_validation import validate_password
from django.contrib.auth import authenticate

#登録処理
class RegistForm(forms.ModelForm):
    school_id = forms.IntegerField(label='ユーザーID')
    class_id = forms.IntegerField(label='出席番号')
    first_name = forms.CharField(label='姓')
    last_name = forms.CharField(label='名')
    first_name_phonetic = forms.CharField(label='姓(ふりがな)') 
    last_name_phonetic = forms.CharField(label='名(ふりがな)') 
    birthday = forms.DateField(label='誕生日') 
    school_grade = forms.IntegerField(label='学年', required=False) #教師が学年や組に属さないパターンあるので必須項目にはしない。
    school_class = forms.IntegerField(label='組', required=False) 
    email = forms.EmailField(label='メールアドレス', required=False)#スマホ持たない学生いそう なので必須項目にはしない。
    club = forms.CharField(label='部活動')
    GENDER_CHOICES = (
        ('man', 'Man'),
        ('woman', 'Woman'),
    )
    STATUS_CHOICES = (
        ('teacher', 'Teacher'),
        ('student', 'Student'),
    ) 
    gender = forms.ChoiceField(label='性別', choices=GENDER_CHOICES) 
    status = forms.ChoiceField(label='学校との関係', choices=STATUS_CHOICES) 
    
    password = forms.CharField(label='パスワード', widget=forms.PasswordInput())
    confirm_password = forms.CharField(label='パスワード再入力', widget=forms.PasswordInput())

    class Meta():
        model = Users
        fields = (
            'school_id',
            'class_id',
            'first_name',
            'last_name',
            'first_name_phonetic',
            'last_name_phonetic',
            'birthday',
            'school_grade',
            'school_class',
            'email',
            'club',
            'gender',
            'status',
            'password',
            )

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data['password']
        confirm_password = cleaned_data['confirm_password']
        if password != confirm_password:
            raise forms.ValidationError('パスワードが一致しません')
    
    def save(self, commit=False):
        user = super().save(commit=False)
        validate_password(self.cleaned_data['password'], user)
        user.set_password(self.cleaned_data['password'])
        user.save()

#ログイン入力欄
class loginForm(forms.Form):
    school_id = forms.CharField(label="ユーザーID")
    password = forms.CharField(label="パスワード", widget=forms.PasswordInput())


#ユーザー情報更新欄
class UserEditForm(forms.ModelForm):
    school_id = forms.IntegerField(label='ユーザーID')
    class_id = forms.IntegerField(label='出席番号')
    first_name = forms.CharField(label='姓')
    last_name = forms.CharField(label='名')
    first_name_phonetic = forms.CharField(label='姓(ふりがな)') 
    last_name_phonetic = forms.CharField(label='名(ふりがな)') 
    school_grade = forms.IntegerField(label='学年', required=False) #教師が学年や組に属さないパターンあるので必須項目にはしない。
    school_class = forms.IntegerField(label='組', required=False) 
    email = forms.EmailField(label='メールアドレス', required=False)#スマホ持たない学生いそう なので必須項目にはしない。
    club = forms.CharField(label='部活動')

    class Meta:
        model = Users
        fields = (
            'school_id',
            'class_id',
            'first_name',
            'last_name',
            'first_name_phonetic',
            'last_name_phonetic',
            'school_grade',
            'school_class',
            'email',
            'club',
            )

class UserDeleteForm(forms.ModelForm):

    class Meta:
        model = Users
        fields = []


class PasswordChangeForm(forms.ModelForm):
    
    old_password = forms.CharField(label='変更前のパスワード', widget=forms.PasswordInput())
    password = forms.CharField(label='新しいパスワード', widget=forms.PasswordInput())
    confirm_password = forms.CharField(label='新しいパスワード再入力', widget=forms.PasswordInput())

    class Meta():
        model = Users
        fields = ('old_password','password','confirm_password')
    
    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data['password']
        confirm_password = cleaned_data['confirm_password']
        old_password = cleaned_data['old_password']
        user = authenticate(password=old_password) 
        if password != confirm_password:
            raise forms.ValidationError('新しいパスワードが異なります')
        if old_password == password:
            raise forms.ValidationError('変更前のパスワードと新しいパスワードは異なるものにしてください')
        if user:
            raise forms.ValidationError('変更前のパスワードが異なります')
            
        
    def save(self, commit=False):
        user = super().save(commit=False)
        validate_password(self.cleaned_data['password'], user)
        user.set_password(self.cleaned_data['password'])
        user.save()
        return user

sample_board/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from . import forms
from django.core.exceptions import ValidationError
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .models import Users
from django.contrib.auth import update_session_auth_hash
# Create your views here.

#ウェルカム画面表示
def welcome(request):
    return render(
        request, 'accounts/welcome.html'
    )

#ホーム画面表示
def home(request):
    return render(
        request, 'accounts/home.html'
    )

#登録処理
def regist(request):
    regist_form = forms.RegistForm(request.POST or None)
    if regist_form.is_valid():
        try: #例外処理
            regist_form.save()
            messages.success(request, f'ユーザー登録をしました。')
            return redirect('accounts:home') 
        except ValidationError as e:
            regist_form.add_error('password', e)
    return render(
        request, 'accounts/regist.html',context={ 
            'regist_form': regist_form,
        }
    )

#新規登録処理
def new_regist(request):
    new_regist_form = forms.RegistForm(request.POST or None)
    if new_regist_form.is_valid():
        try: #例外処理
            new_regist_form.save()
            messages.success(request, f'新規のユーザー登録をしました。ログインを行ってください。')
            return redirect('accounts:home') 
        except ValidationError as e:
            new_regist_form.add_error('password', e)
    return render(
        request, 'accounts/new_regist.html',context={ 
            'new_regist_form': new_regist_form,
        }
    )

#ログイン処理
def login_user(request):
    login_form = forms.loginForm(request.POST or None)
    if login_form.is_valid(): 
        school_id = login_form.cleaned_data.get('school_id') 
        password = login_form.cleaned_data.get('password')
        user = authenticate(school_id=school_id, password=password) 
        if user: 
            if user.is_active:  #userが認証されている場合
                login(request, user) 
                messages.success(request, f'ログインしました')
                return redirect('accounts:home') 
            else: #user認証されていない場合
                messages.warning(request, 'ユーザーが登録されていません') 
        else: #(学籍番号とパスワードが一致した)userが取得できなかった場合
            messages.warning(request, '学籍番号かパスワードが間違っています')
    
    return render( 
        request, 'accounts/login.html', context={ 
            'login_form': login_form, 
        }
    )

#ログアウト処理
@login_required 
def logout_user(request):  
    logout(request) 
    messages.success(request, 'ログアウトしました') 
    return redirect('accounts:welcome') 

#ユーザー情報更新処理
@login_required
def edit_user(request):
    user_edit_form = forms.UserEditForm(request.POST or None, request.FILES or None)
    if user_edit_form.is_valid():
        messages.success(request, '更新完了しました')
        user_edit_form.save()
    return render(request, 'accounts/edit.html', context={
        'user_edit_form': user_edit_form,
    })

#アカウント削除処理
@login_required
def delete_user(request, **kwargs):
    user = get_object_or_404(Users, **kwargs)
    delete_user_form = forms.UserDeleteForm(request.POST or None)
    if delete_user_form.is_valid():
        user.delete()
        messages.success(request, 'ユーザーアカウントを削除しました')
        return redirect('accounts:welcome')
    return render(
        request, 'accounts/delete.html', context={
            'delete_user_form': delete_user_form
        }
    )

#パスワード変更処理
@login_required
def change_password(request):
    password_change_form = forms.PasswordChangeForm(request.POST or None, instance=request.user)
    if password_change_form.is_valid():
        try:
            password_change_form.save()
            messages.success(request, 'パスワード更新完了しました')
            update_session_auth_hash(request, request.user)
        except ValidationError as e:
            password_change_form.add_error('password', e)
    return render(
        request, 'accounts/change_password.html', context={
            'password_change_form': password_change_form
        }
    )

sample_board/templates/accounts/change_password.html
{% extends "base.html" %}
{% block content %}
{% if messages %}
    {% for message in messages %}
        <div>{{ message.message }}</div>
    {% endfor %}
{% endif %}
<form method="POST">
{% csrf_token %}
{{ password_change_form.as_p }}
<div class="buttons">
    <input class="execution-button" type="submit" value="パスワード更新">
    <a class="return-button" href="{% url 'accounts:edit' %}">ユーザー情報更新画面に戻る</a>
</div>
</form>
{% endblock %}

sample_board/templates/accounts/delete.html
{% extends "base.html" %}
{% block content %}
<h1>アカウント削除画面</h1>
<form method="POST" class="border 1px solid lg">
{% csrf_token %}
{{ delete_user_form.as_p }}
<p class=message>本当にアカウントを削除してもよろしいですか？</p><br>

<div class="buttons">
    <input class="delete-button" type="submit" value="ユーザ削除">
    <a class="return-button" href="{% url 'accounts:edit' %}">戻る</a>
</div>

<p>アカウントを削除すると、ログアウトしてwelcomeページに移動します。</p>
</form>
{% endblock %}

sample_board/templates/accounts/edit.html
{% extends "base.html" %}
{% block content %}
{% if messages %}
    {% for message in messages %}
        <div>{{ message.message }}</div>
    {% endfor %}
{% endif %}
<form method="POST" enctype="multipart/form-data" >
<h1>ユーザー情報更新画面</h1>
{% csrf_token %}
{{ user_edit_form.as_p }}
<div class="buttons">
    <a id="password-button" href="{% url 'accounts:change_password' %}">パスワード変更</a>
    <input class="execution-button" type="submit" value="更新">
    <a class="delete-button" href="{% url 'accounts:delete' id=user.id  %}">ユーザー削除</a>
    <a class="return-button" href="{% url 'accounts:home' %}">ホームに戻る</a>
</div>
</form>
{% endblock %}

sample_board/templates/accounts/home.html
{% extends 'base.html' %}
{% block content %}
{% if messages %}
{% for message in messages %}
    <div>{{ message.message }}</div>
{% endfor %}
{% endif %}

<h1>ホーム画面</h1>

<p>このアプリは学校の先生からの連絡を家庭で閲覧できることを目的として作られたアプリです。以下の通りの機能を持っています。</p>

<div id='function-introduce'>
    <h2>各機能紹介</h2>
    <ul>
        <li>ユーザー情報更新</li>
        <p>ユーザー登録時の情報を編集、また、登録されたユーザーの削除ができます。</p>
        <li>掲示板一覧</li>
        <p>教師アカウントは掲示板の作成、編集、削除が可能です。また、各掲示板でコメントの投稿、編集、削除が可能です。</p>
        <p>生徒、アカウントは掲示板の閲覧、各掲示板のコメントの閲覧が可能です。</p>
        <li>掲示板検索</li>
        <p>掲示板の名前を検索することが可能です。</p>
    </ul>
</div>



{% endblock %}

sample_board/templates/accounts/login.html
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="utf-8">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <style>
        p, div, h1 {
            margin:20px 20px;
            padding:20px 40px ;
            text-align: center;
        }
        .testaccountinfo {
            padding: 10px;
            border: double 1px black;
            background: silver;
        }

        #welcomebutton {
            display:flex;
        }

        .button{
            padding: 5px 10px;
            margin: 20px 60px;
            border: 1px solid rgb(190, 190, 190);
            background: rgb(54, 54, 54);
            color: white;
        }

        .account-name{
            font-weight: bold
        }

        .execution-button{
            padding: 5px 10px;
            margin: 20px 60px;
            border: 1px solid rgb(190, 190, 190);
            background: rgb(85, 253, 93);
            color: white;
        }

        .return-button{
            padding: 5px 10px;
            margin: 20px 60px;
            border: 1px solid rgb(190, 190, 190);
            background: rgb(100, 167, 243);
            color: white;
        }
        </style>
        <h1>ログイン画面</h1>
    </head>
    <body>
        <form method="POST">
            {% if messages %}
            {% for message in messages %}
            <p><div>{{ message.message }}</div></p>
            {% endfor %}
            {% endif %}
            {% csrf_token %}
            {{ login_form.as_p }}
            <div class="buttons">
                <input class="execution-button" type="submit" value="ログイン">
                <a class="return-button" href="{% url 'accounts:welcome' %}">welcomeページに戻る</a>
            </div>
            <div class="testaccountinfo"><p>ログイン用テストアカウント</p>
                <a class='account-name'>教師用アカウント</a><br>
                <a>ユーザーID:1111<br>
                パスワード:test1test1</a><br><br>
                
                
                <a class='account-name'>生徒用アカウント</a><br>
                <a>ユーザーID(学籍番号):270001<br>
                パスワード:sampletarou270001<br><br>
                ログイン画面で上記の情報を入力するとログインできます。</a>
            </div>
        </form>
    </body>
</html>

sample_board/templates/accounts/new_regist.html
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="utf-8">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <style>
        .execution-button{
            padding: 5px 10px;
            margin: 20px 60px;
            border: 1px solid rgb(190, 190, 190);
            background: rgb(85, 253, 93);
            color: white;
        }

        .return-button{
            padding: 5px 10px;
            margin: 20px 60px;
            border: 1px solid rgb(190, 190, 190);
            background: rgb(100, 167, 243);
            color: white;
        }

        .delete-button{
            padding: 5px 10px;
            margin: 20px 60px;
            border: 1px solid rgb(190, 190, 190);
            background: rgb(247, 99, 40);
            color: white;
        }

        .buttons{
            display: flex;
            padding: 5px 10px;
        }
        </style>
        <h1>新規ユーザー登録画面</h1>

    </head>
    <body>
        <form method="POST">
            {% csrf_token %}
            {{ new_regist_form.as_p }}
            <div class="buttons">
                <input class="execution-button" type="submit" value="ユーザ登録">
                <a class="return-button" href="{% url 'accounts:welcome' %}">welcomeページに戻る</a>
            </div>
        </form>
    </body>
</html>

sample_board/templates/accounts/regist.html
{% extends "base.html" %}
{% block content %}
<form method="POST">
<h1>ユーザー登録画面</h1>
{% csrf_token %}
{{ regist_form.as_p }}
<div class="buttons">
    <input class="execution-button" type="submit" value="ユーザ登録">
    <a class="return-button" href="{% url 'accounts:home' %}">ホーム画面に戻る</a>
</div>
</form>
{% endblock %}

sample_board/templates/accounts/welcome.html
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="utf-8">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <style>
        p, div, h1 ,h3{
            margin:20px 20px;
            padding:20px 40px;
            text-align: center;
        }
        .testaccountinfo {
            padding: 10px;
            border: 1px solid black;
            background: silver;
        }
        #welcomebutton {
            display:flex;
        }

        .button{
            padding: 5px 10px;
            margin: 20px 60px;
            border: 1px solid rgb(190, 190, 190);
            background: rgb(54, 54, 54);
            color: white;
        }

        .account-name{
            font-weight: bold
        }
        </style>
        <title>教師と生徒の学校連絡掲示板</title>
        <h1>学校連絡掲示板</h1>
        <h3>welcomeページ</h3>
    </head>

    <body>  
        {% if messages %}
        {% for message in messages %}
            <p><div>{{ message.message }}</div></p>
        {% endfor %}
        {% endif %}
        <div id="welcomebuttons">
            <a class="button" href="{% url 'accounts:new_regist' %}">新規ユーザー登録</a>
            <a class="button" href="{% url 'accounts:login' %}">ログイン</a>
        </div> 
        <div class="testaccountinfo"><p>ログイン用テストアカウント</p>
            <a class='account-name'>教師用アカウント</a>
            <a>ユーザーID:1111<br>
            パスワード:test1test1<br><br>
            
            <a class='account-name'>生徒用アカウント</a>
            <a>ユーザーID(学籍番号):270001<br>
            パスワード:sampletarou270001<br><br>
            ログイン画面で上記の情報を入力するとログインできます。</a>
        </div>
    </body>
</html>